routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');
//->middleware('auth');
Route::middleware(['auth'])->group(function () {
    Route::resource('companies', 'CompaniesController');
    Route::get('projects/create/{company_id?}', 'ProjectsController@create');
    Route::resource('projects', 'ProjectsController');

    Route::resource('roles', 'RolesController');
    Route::resource('tasks', 'TasksController');
    Route::resource('users', 'UsersController');
    Route::resource('comments', 'CommentController');

});

app/Project.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
    //
    protected $fillable = [
        'name',
        'description',
        'company_id',
        'user_id',
        'days',

    ];

    public function user() {
        return $this->belongsToMany('App\User');
    }

    public function company() {
        return $this->belongsTo('App\Company');
    }

    public function comments()
    {
        return $this->morphMany('App\Comment', 'commentable');
    }

}

app/Http/Controllers/ProjectsController.php
<?php

namespace App\Http\Controllers;

use App\Project;
use App\Company;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class ProjectsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        if (Auth::check()){
            $projects = Project::where('user_id', Auth::user()->id)->get();

            return view('projects.index', ['projects' => $projects]);
        }
        return view('auth.login');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create( $company_id = null )
    {
        //

        $companies = null;
        if(!$company_id){
            $companies = Company::where('user_id', Auth::user()->id)->get();
        }

        return view('projects.create',['company_id'=>$company_id, 'companies'=>$companies]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        if (Auth::check()){
            $project = Project::create([
                'name'=>$request->input('name'),
                'description' =>$request->input('description'),
                'company_id' => $request->input('company_id'),
                'user_id' => Auth::user()->id,
            ]);
            if ($project){
                return redirect()->route('projects.show', ['project'=> $project->id])
                    ->with('success', 'project created successfully');
            }
        }
        return back()->withInput()->with('errors', 'Error create new project');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\project  $project
     * @return \Illuminate\Http\Response
     */
    public function show(Project $project)
    {
        //
        $project = Project::find($project->id);

        return view('projects.show', ['project'=>$project]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\project  $project
     * @return \Illuminate\Http\Response
     */
    public function edit(Project $project)
    {
        //
        $project = Project::find($project->id);

        return view('projects.edit',['project'=>$project]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\project  $project
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Project $project)
    {
        //save data

        $projectUpdate = Project::where('id',$project->id)
            ->update([
                'name' => $request->input('name'),
                'description' => $request->input('description')
            ]);
        if ($projectUpdate){
            return redirect()->route('projects.show',['project' =>$project->id])->with('success','project updated  success');
        }
        //redirect
        return back()->withInput();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\project  $project
     * @return \Illuminate\Http\Response
     */
    public function destroy(Project $project)
    {
//redirect
        $findproject = Project::find( $project->id);
        if ($findproject->delete()){
            return redirect()->route('projects.index')
                ->with('success' , 'project deleted successfully');
        }
        return back()->withInput()->with('error' , 'project could not be Deleted');
    }
}

resources/views/projects/create.blade.php
@extends('layouts.app')

@section('content')

    <div class="col-md-9 col-lg-9 col-sm-9 pull-left">

        <div class="row col-md-12 col-lg-12 col-sm-12" style="background: white;">
            <h1>Create New Project</h1>
            <form action="{{ route('projects.store') }}" method="post">
                {{ csrf_field() }}


                <div class="form-group">
                    <lable for="project-name">Name <span class="required">*</span></lable>
                    <input placeholder="Enter name"
                           id="project-name"
                           required
                           name="name"
                           spellcheck="false"
                           class="form-control"
                    >
                    <input type="hidden"
                           name="company_id"
                           value="{{ $company_id }}"
                    >
                </div>
                <div class="form-group">
                    <label for="project-content">Description</label>
                    <textarea placeholder="Enter description"
                              id="project-content"
                              required
                              name="description"
                              rows="5" spellcheck="false"
                              class="form-control autosize-target text-left">

                    </textarea>
                </div>
                <div class="form-group">
                    <input type="submit" class="btn btn-primary pull-right" value="submit">
                </div>
            </form>
        </div>
    </div>

    <div class="col-sm-3 col-md-3 col-lg-3 pull-right">
        <div class="sidebar-module">
            <h4>Action</h4>
            <ol class="list-unstyled">
                <li><a href="/projects">My projects</a></li>

            </ol>
        </div>
    </div>
@endsection

resources/views/projects/edit.blade.php
@extends('layouts.app')

@section('content')

    <div class="col-md-9 col-lg-9 col-sm-9 pull-left">

        <div class="row col-md-12 col-lg-12 col-sm-12" style="background: white; margin: 10px">
            <form action="{{ route('companies.update',[$company->id]) }}" method="post">
                {{ csrf_field() }}

                <input type="hidden" name="_method" value="patch">

                <div class="form-group">
                    <lable for="company-name">Name <span class="required">*</span></lable>
                    <input placeholder="Enter name"
                           id="company-name"
                           required
                           name="name"
                           spellcheck="false"
                           class="form-control"
                           value="{{ $company->name }}"
                    >
                </div>
                <div class="form-group">
                    <label for="company-content">Description</label>
                    <textarea placeholder="Enter description"
                           id="company-content"
                           required
                           name="description"
                           rows="5" spellcheck="false"
                           class="form-control autosize-target text-left">
                           {{ $company->description }}
                    </textarea>
                </div>
                <div class="form-group">
                    <input type="submit" class="btn btn-primary pull-right" value="submit">
                </div>
            </form>
        </div>
    </div>

    <div class="col-sm-3 col-md-3 col-lg-3 pull-right">
        <div class="sidebar-module">
            <h4>Action</h4>
            <ol class="list-unstyled">
                <li><a href="/companies/{{ $company->id }}">View Companies</a></li>
                <li><a href="/companies">All Companies</a></li>

            </ol>
        </div>
    </div>
@endsection

resources/views/projects/index.blade.php
@extends('layouts.app')

@section('content')

    <div class="col-md-6 col-lg-6 col-md-offset-3  col-lg-offset-3">
        <div class="panel panel-primary ">
            <div class="panel-heading">Projects <a  class="pull-right btn btn-primary btn-sm" href="/projects/create">
                    Create new</a> </div>
            <div class="panel-body">


                <ul class="list-group">
                    @foreach($projects as $project)
                        <li class="list-group-item">
                            <i class="fa fa-play" aria-hidden="true"></i>
                            <a href="/projects/{{ $project->id }}" >{{ $project->name }}</a></li>
                    @endforeach
                </ul>


            </div>
        </div>
    </div>

@endsection

resources/views/projects/show.blade.php
@extends('layouts.app')

@section('content')

    <div class="col-md-9 col-lg-9 col-sm-9 pull-left">
        <!-- The justified navigation menu is meant for single line per list item.
             Multiple lines will require custom code not provided by Bootstrap. -->

        <!-- Jumbotron -->
        <div class="well well-lg">
            <h1>{{ $project->name }}</h1>
            <p class="lead">{{ $project->description }}</p>
            {{--<p><a class="btn btn-lg btn-success" href="#" role="button">Get started today</a></p>--}}
        </div>

        <div class="row col-md-12 col-lg-12 col-sm-12" style="background: white; margin: 10px">
            <a href="/projects/create/{{ $project->id }}" class="pull-right btn btn-success btn-sm">Add Project</a>
            <br>

            <div class="row container-fluid">

                <form method="post" action="{{ route('comments.store') }}">
                    {{ csrf_field() }}


                    <input type="hidden" name="commentable_type" value="Project">
                    <input type="hidden" name="commentable_id" value="{{$project->id}}">


                    <div class="form-group">
                        <label for="comment-content">Comment</label>
                        <textarea placeholder="Enter comment"
                                  style="resize: vertical"
                                  id="comment-content"
                                  name="body"
                                  rows="3" spellcheck="false"
                                  class="form-control autosize-target text-left">


                                          </textarea>
                    </div>


                    <div class="form-group">
                        <label for="comment-content">Proof of work done (Url/Photos)</label>
                        <textarea placeholder="Enter url or screenshots"
                                  style="resize: vertical"
                                  id="comment-content"
                                  name="url"
                                  rows="2" spellcheck="false"
                                  class="form-control autosize-target text-left">


                                          </textarea>
                    </div>


                    <div class="form-group">
                        <input type="submit" class="btn btn-primary pull-right"
                               value="Submit"/>
                    </div>
                </form>



            </div>

        </div>
    </div>

    <div class="col-sm-3 col-md-3 col-lg-3 pull-right">
        <div class="sidebar-module">
            <h4>Action</h4>
            <ol class="list-unstyled">
                <li><a href="/projects/{{ $project->id }}/edit">Edit</a></li>
                <li><a href="/project/create">Create New project</a></li>
                <li><a href="/projects">My projects</a></li>

                <br>
                @if($project->user_id == Auth::user()->id)
                <li>
                    <a href="#"
                    onclick="
                    var result = confirm('Are you sure you wish to delete this Project?');
                    if(result)
                    {
                    event.preventDefault();
                    document.getElementById('delete-form').submit();
                    }
                    "
                    >
                    Delete
                    </a>
                    <form id="delete-form" action="{{ route('projects.destroy',[$project->id]) }}"
                          method="post" style="display: none;">
                        <input type="hidden" name="_method" value="delete">
                        {{ csrf_field() }}
                    </form>
                </li>
                @endif
                {{--<li><a href="#">Add new member</a></li>--}}
            </ol>
        </div>
        {{--<div class="sidebar-module">--}}
            {{--<h4>Member</h4>--}}
            {{--<ol class="list-unstyled">--}}
                {{--<li><a href="#">March 2014</a></li>--}}
                {{----}}
            {{--</ol>--}}
        {{--</div>--}}

    </div>
@endsection