routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');
//->middleware('auth');
Route::middleware(['auth'])->group(function () {
    Route::resource('companies', 'CompaniesController');
    Route::get('projects/create/{company_id?}', 'ProjectsController@create');
    Route::resource('projects', 'ProjectsController');

    Route::resource('roles', 'RolesController');
    Route::resource('tasks', 'TasksController');
    Route::resource('users', 'UsersController');
    Route::resource('comments', 'CommentController');

});

app/Company.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Company extends Model
{
    //
    protected $fillable = [
        'name',
        'description',
        'user_id'

    ];

    public function user() {
        return $this->belongsToMany('App\User');
    }

    public function projects() {
        return $this->hasMany('App\Project');
    }

    public function comments()
    {
        return $this->morphMany('App\Comment', 'commentable');
    }
}

app/Http/Controllers/CompaniesController.php
<?php

namespace App\Http\Controllers;

use App\Company;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class CompaniesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        if (Auth::check()){
            $companies = Company::where('user_id', Auth::user()->id)->get();

            return view('companies.index', ['companies' => $companies]);
        }
        return view('auth.login');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('companies.create');

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        if (Auth::check()){
            $company = Company::create([
                'name'=>$request->input('name'),
                'description' =>$request->input('description'),
                'user_id' => Auth::user()->id,
            ]);
            if ($company){
                return redirect()->route('companies.show', ['company'=> $company->id])
                    ->with('success', 'Company created successfully');
            }
        }
        return back()->withInput()->with('errors', 'Error create new company');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function show(Company $company)
    {
        //
        $company = Company::find($company->id);

        return view('companies.show', ['company'=>$company]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function edit(Company $company)
    {
        //
        $company = Company::find($company->id);

        return view('companies.edit',['company'=>$company]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Company $company)
    {
        //save data

        $companyUpdate = Company::where('id',$company->id)
            ->update([
                'name' => $request->input('name'),
                'description' => $request->input('description')
            ]);
        if ($companyUpdate){
            return redirect()->route('companies.show',['company' =>$company->id])->with('success','Company updated  success');
        }
        //redirect
        return back()->withInput();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function destroy(Company $company)
    {
//redirect
        $findCompany = Company::find( $company->id);
        if ($findCompany->delete()){
            return redirect()->route('companies.index')
                ->with('success' , 'Company deleted successfully');
        }
        return back()->withInput()->with('error' , 'Company could not be Deleted');
    }
}

resources/views/companies/create.blade.php
@extends('layouts.app')

@section('content')

    <div class="col-md-9 col-lg-9 col-sm-9 pull-left">

        <div class="row col-md-12 col-lg-12 col-sm-12" style="background: white; margin: 10px">
            <h1>Create New Company</h1>
            <form action="{{ route('companies.store') }}" method="post">
                {{ csrf_field() }}


                <div class="form-group">
                    <lable for="company-name">Name <span class="required">*</span></lable>
                    <input placeholder="Enter name"
                           id="company-name"
                           required
                           name="name"
                           spellcheck="false"
                           class="form-control"
                    >
                </div>
                <div class="form-group">
                    <label for="company-content">Description</label>
                    <textarea placeholder="Enter description"
                              id="company-content"
                              required
                              name="description"
                              rows="5" spellcheck="false"
                              class="form-control autosize-target text-left">

                    </textarea>
                </div>
                <div class="form-group">
                    <input type="submit" class="btn btn-primary pull-right" value="submit">
                </div>
            </form>
        </div>
    </div>

    <div class="col-sm-3 col-md-3 col-lg-3 pull-right">
        <div class="sidebar-module">
            <h4>Action</h4>
            <ol class="list-unstyled">
                <li><a href="/companies">My Companies</a></li>

            </ol>
        </div>
    </div>
@endsection

resources/views/companies/edit.blade.php
@extends('layouts.app')

@section('content')

    <div class="col-md-9 col-lg-9 col-sm-9 pull-left">

        <div class="row col-md-12 col-lg-12 col-sm-12" style="background: white; margin: 10px">
            <form action="{{ route('companies.update',[$company->id]) }}" method="post">
                {{ csrf_field() }}

                <input type="hidden" name="_method" value="patch">

                <div class="form-group">
                    <lable for="company-name">Name <span class="required">*</span></lable>
                    <input placeholder="Enter name"
                           id="company-name"
                           required
                           name="name"
                           spellcheck="false"
                           class="form-control"
                           value="{{ $company->name }}"
                    >
                </div>
                <div class="form-group">
                    <label for="company-content">Description</label>
                    <textarea placeholder="Enter description"
                           id="company-content"
                           required
                           name="description"
                           rows="5" spellcheck="false"
                           class="form-control autosize-target text-left">
                           {{ $company->description }}
                    </textarea>
                </div>
                <div class="form-group">
                    <input type="submit" class="btn btn-primary pull-right" value="submit">
                </div>
            </form>
        </div>
    </div>

    <div class="col-sm-3 col-md-3 col-lg-3 pull-right">
        <div class="sidebar-module">
            <h4>Action</h4>
            <ol class="list-unstyled">
                <li><a href="/companies/{{ $company->id }}">View Companies</a></li>
                <li><a href="/companies">All Companies</a></li>

            </ol>
        </div>
    </div>
@endsection

resources/views/companies/index.blade.php
@extends('layouts.app')

@section('content')

    <div class="col-md-6 col-lg-6 col-md-offset-3 col-lg-offset-3">
        <div class="panel panel-primary ">
            <div class="panel-heading">Companies <a  class="pull-right btn btn-primary btn-sm" href="/companies/create">Create New</a></div>
            <div class="panel-body">

                <ul class="list-group">
                    @foreach($companies as $company)
                        <li class="list-group-item"><a href="/companies/{{ $company->id }}">{{ $company->name }}</a></li>
                    @endforeach
                </ul>

            </div>
        </div>
    </div>

@endsection

resources/views/companies/show.blade.php
@extends('layouts.app')

@section('content')

    <div class="col-md-9 col-lg-9 col-sm-9 pull-left">
        <!-- The justified navigation menu is meant for single line per list item.
             Multiple lines will require custom code not provided by Bootstrap. -->

        <!-- Jumbotron -->
        <div class="jumbotron">
            <h1>{{ $company->name }}</h1>
            <p class="lead">{{ $company->description }}</p>
            {{--<p><a class="btn btn-lg btn-success" href="#" role="button">Get started today</a></p>--}}
        </div>

        <div class="row col-md-12 col-lg-12 col-sm-12" style="background: white; margin: 10px">
            <a href="/projects/create/{{ $company->id }}" class="pull-right btn btn-success btn-sm">Add Project</a>
            @foreach($company->projects as $project)
                <div class="col-lg-4 col-md-4 col-sm-4">
                    <h2>{{ $project->name }}</h2>
                    <p class="text-danger">{{ $project->description }}</p>
                    <p><a class="btn btn-primary" href="/projects/{{ $project->id }}" role="button">View details »</a>
                    </p>
                </div>
            @endforeach
        </div>
    </div>

    <div class="col-sm-3 col-md-3 col-lg-3 pull-right">
        <div class="sidebar-module">
            <h4>Action</h4>
            <ol class="list-unstyled">
                <li><a href="/companies/{{ $company->id }}/edit">Edit</a></li>
                <li><a href="/projects/create/{{ $company->id }}">Add project</a></li>
                <li><a href="/companies">My Companies</a></li>
                <li><a href="/company/create">Create New Company</a></li>
                <br>
                <li>
                    <a href="#"
                    onclick="
                    var result = confirm('Are you sure you wish to delete this Project?');
                    if(result)
                    {
                    event.preventDefault();
                    document.getElementById('delete-form').submit();
                    }
                    "
                    >
                    Delete
                    </a>
                    <form id="delete-form" action="{{ route('companies.destroy',[$company->id]) }}"
                          method="post" style="display: none;">
                        <input type="hidden" name="_method" value="delete">
                        {{ csrf_field() }}
                    </form>
                </li>
                {{--<li><a href="#">Add new member</a></li>--}}
            </ol>
        </div>
        {{--<div class="sidebar-module">--}}
            {{--<h4>Member</h4>--}}
            {{--<ol class="list-unstyled">--}}
                {{--<li><a href="#">March 2014</a></li>--}}
                {{----}}
            {{--</ol>--}}
        {{--</div>--}}

    </div>
@endsection